			<?php $pagetitle = 'Member Approved!'; ?>
				<!---pag nag aadd ka ng content, etong div lang na ito ang babaguhin.^^--->
				<div name="contentBox" style="background: transparent;">
					<h1><?php echo $pagetitle;?></h1>
					<p style="margin-left:40px; margin-right:35px;">
					Member has been given researcher access to our website.<br />
					Please click <a href="./approveresearcher.php">here</a> to see the list of pending accounts for approval.
					</p>
					</div>
			
		