			<?php $pagetitle = 'About this site'; ?>
				<!---pag nag aadd ka ng content, etong div lang na ito ang babaguhin.^^--->
					<h1><?php echo $pagetitle;?></h1>
					<p style="margin-left:30px; margin-right:35px; text-indent:15px;">
					This information management system is being presented in partial fulfillment of the requirements for the completion of the course, Software Engineering.</p>
			<p style="margin-left:50px;">This site is maintained by the following:</p>
			<table style="margin-left:60px;">
				<tr>
					<td width="75%">Buban, Regina Renzy</td>
				</tr>
				<tr>
					<td width="75%">Ghany, Mark Lester</td>
				</tr>
				<tr>
					<td width="75%">Manzano, Ma. Trixe Mavell</td>
				</tr>
				<tr>
					<td width="75%">Vinas, Ismael</td>
				</tr>
				</table>                    
			</td>
		</tr>